<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/home.css">

<!-- Message de notification -->

<!-- Code HTML à écrire -->

<p id="home-presentation">Le site de vente de bière le plus côté du marché du poivrot, ici vous trouverez les meilleures bières, 
de la 86 à la kronembourg. Nous mettons un point d'honneur à vous la facturer chère et à vous livrer tiède.</p>


<!-- Liste des aliments -->
<img id="homerHome" class="" src="<?= $wwwUrl?>/images/logo/kroHome.jpg"/>


<div class="c-b"></div>